security:
    role_hierarchy:
        ROLE_ADMIN:     ROLE_VERIFIER
        ROLE_VERIFIER:  ROLE_COLLECTOR
        ROLE_COLLECTOR: ROLE_READER
        ROLE_READER:    ROLE_USER

    providers:
        users:
            entity: { class: 'Paho\Vinuva\Models\User', property: 'email' }
    encoders:
        Paho\Vinuva\Models\User:
            algorithm: argon2i

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login: true
            user_checker: App\Security\UserChecker
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/meningitis, roles: ROLE_COLLECTOR }
        - { path: ^/pneumonia, roles: ROLE_COLLECTOR }
        - { path: ^/rotavirus, roles: ROLE_COLLECTOR }
        - { path: ^/, roles: ROLE_USER }
