twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        '%kernel.project_dir%/vendor/ns/color-admin-bundle/src/Resources/views': ColorAdmin
        '%kernel.project_dir%/templates': App
