monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: deduplicated
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        deduplicated:
            type:    deduplication
            handler: swift
        swift:
            type:       swift_mailer
            from_email: 'noreply@vinuvacasos.org'
            to_email:   'nathanael@noblet.ca'
            # or list of recipients
            # to_email:   ['dev1@example.com', 'dev2@example.com', ...]
            subject:    'ERROR: Vinuva Aggregate %%message%%'
            level:      error
            formatter:  monolog.formatter.html
            content_type: text/html
        grouped:
            type:    group
            members: [streamed, deduplicated]
        streamed:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
