login_check:
  path: /login_check

logout:
  path: /logout

JMSTranslationBundle_ui:
  resource: "@JMSTranslationBundle/Controller/"
  type:     annotation
  prefix:   /_trans

login:
  path: /login
  controller: App\Controller\SecurityController::loginAction

forgotPassword:
  path: /forgot-password
  controller: App\Controller\SecurityController::forgotAction

resetPassword:
  path: /reset-password/{token}
  controller: App\Controller\SecurityController::resetPasswordAction

homepage_no_locale:
  path: /
  controller: App\Controller\DefaultController::noLocaleAction
