parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/App/*'
        exclude: '../src/App/{DependencyInjection,Entity,Migrations,Kernel.php}'

    App\Controller\:
        resource: '../src/App/Controller'
        tags: ['controller.service_arguments']

    Paho\Vinuva\Repositories\PneumoniaRepository:
        arguments:
            $class: Paho\Vinuva\Models\Pneumonia

    Paho\Vinuva\Repositories\MeningitisRepository:
        arguments:
            $class: Paho\Vinuva\Models\Pneumonia

    Paho\Vinuva\Repositories\RotavirusRepository:
        arguments:
            $class: Paho\Vinuva\Models\Pneumonia
