parameters:
    locale: 'en'
    ns.color_admin.menu_builder: App\Menu\MenuBuilder

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/App/*'
        exclude: '../src/App/{DependencyInjection,Entity,Migrations,Kernel.php}'

    App\Controller\:
        resource: '../src/App/Controller'
        tags: ['controller.service_arguments']

    Paho\Vinuva\Repositories\PneumoniaRepository:
        arguments:
            $class: Paho\Vinuva\Models\Pneumonia

    Paho\Vinuva\Repositories\MeningitisRepository:
        arguments:
            $class: Paho\Vinuva\Models\Meningitis

    Paho\Vinuva\Repositories\RotavirusRepository:
        arguments:
            $class: Paho\Vinuva\Models\Rotavirus

    Paho\Vinuva\Validator\ProbableValidator: ~
