---
- hosts: "{{target}}"
  user: root
  become: true
  become_user: who
  roles:
    - servergrove.symfony2
  vars:
    symfony_project_root: /var/www/vhosts/vinuvacasos.org/aggregate
    symfony_project_name: nuvi
    symfony_project_composer_path: "{{symfony_project_root}}/shared/composer.phar"
    symfony_project_repo: https://github.com/IBVPD/vinuva.git
    symfony_project_env: prod
    symfony_project_console_command: bin/console
    symfony_project_config_dir: config
    symfony_project_console_opts: '--no-debug'
    symfony_project_keep_releases: 15

    symfony_project_branch: master
    symfony_project_php_path: /usr/bin/php73
    symfony_project_php_options: ''

    symfony_project_composer_opts: '--optimize-autoloader --no-interaction'
    symfony_project_shared_folders: # folders to be linked from shared directory to release dir
      - {name: log, src: var/log, path: var/log}

    symfony_project_managed_folders: # folders to be created/checked in release dir
      - {name: cache, path: var/cache}

  tasks:
    - name: Reload php-fpm
      service: name=php73-php-fpm state=reloaded
      become: false
